### ISSUE TITLE
Unable to send close code

### ISSUE THREAD

**Issue by chris-feist** [fanout/node-faas-grip#1]
I am attempting to open a connection and to immediately close it. However, the close code is never passed back to the client. It appears to be missing in the generated response. Here is what my code looks like:
```
    const ws = faasGrip.lambdaGetWebSocket(event);

    if (ws.isOpening()) {
      ws.accept();
    }

    ws.close(1008); // Try any value, and it doesn't work

    callback(null, ws.toResponse());
```

Logging out the response sent to the lambda callback:
```
{
  isBase64Encoded: true,
  statusCode: 200,
  headers: {
    'Content-Type': 'application/websocket-events',
    'Sec-WebSocket-Extensions': 'grip'
  },
  body: 'T1BFTg0KQ0xPU0UgMg0KAAANCg=='
}
```

Logging out `wsContext`:
```
{
  "id": "3f4482a1-20dd-44b4-9641-ba536e2a8667",
  "inEvents": [{
    "type": "OPEN",
    "content": null
  }],
  "readIndex": 0,
  "accepted": true,
  "closeCode": null,
  "closed": true,
  "outCloseCode": 1008,
  "outEvents": [],
  "origMeta": {},
  "meta": {},
  "prefix": ""
}
```

**Comment by jkarneges** [comment]
Weird, in your report the object state looks right, but the response body decodes to:

```
OPEN\r\nCLOSE 2\r\n\x00\x00\r\n
```
(C-escaped for readability)

That's a status code of 0.

Are you using the latest faas-grip and grip library versions?

Here's a test program I tried running locally that generates the correct response for me:

```js
var faasGrip = require('faas-grip');

var ws = faasGrip.lambdaGetWebSocket({
    httpMethod: 'POST',
    headers: { 'Content-Type': 'application/websocket-events' },
    body: 'OPEN\r\n'
})

ws.accept();
ws.close(1008);

console.log(ws);
console.log(ws.toResponse());
```

It prints:

```
{ id: undefined,
  inEvents: [ { type: 'OPEN', content: null } ],
  readIndex: 0,
  accepted: true,
  closeCode: null,
  closed: true,
  outCloseCode: 1008,
  outEvents: [],
  origMeta: {},
  meta: {},
  prefix: '',
  toResponse: [Function] }
{ isBase64Encoded: true,
  statusCode: 200,
  headers: 
   { 'Content-Type': 'application/websocket-events',
     'Sec-WebSocket-Extensions': 'grip' },
  body: 'T1BFTg0KQ0xPU0UgMg0KA/ANCg==' }
```

As expected, the body decodes to:

```
OPEN\r\nCLOSE 2\r\n\x03\xf0\r\n
```

0x03f0 = 1008

**Comment by chris-feist** [comment]
@jkarneges  That is my mistake, I was on an old version of `fass-grip` (1.0.2). It appears to be sending the correct response now. My lambda is being invoked twice, the first time for the open event returning `T1BFTg0KQ0xPU0UgMg0KA/ANCg==` and the second time for the close event returning `Q0xPU0UgMg0KA/ANCg==`.

However, my client is not receiving the proper close code. I've used both my web client and a command line utility ([wscat](https://www.npmjs.com/package/wscat)), and both are reporting a close code of 752 with the above lambda invocations. Do you guys have a separate support channel to get help with that?

**Comment by chris-feist** [comment]
Also, are there any plans for close reason support? I saw its not in the spec: https://pushpin.org/docs/protocols/websocket-over-http/

**Comment by jkarneges** [comment]
A close code of 1008 being reported as 752 sounds like a bug. If you're using Fanout Cloud, best way to report bugs is to email info@fanout.io.

You're free to report such issues to Pushpin directly, e.g. as a GitHub issue or in the chat room, if you have a hunch that's where the problem is, but we don't expect Fanout Cloud users to have to guess which of our server components may have a problem.

Filed an issue about close reasons here: https://github.com/fanout/pushpin/issues/47660

Technically, close reasons aren't an issue with the WebSocket-over-HTTP protocol per se, since event content is raw bytes. Just need Pushpin and the backend to actually read/write the reason data.

**Comment by chris-feist** [comment]
Great, thanks!
